In [1]:
from nequix.data import AseDBDataset

In [2]:
dataset = AseDBDataset(file_path="/ceph/hdd/students/kirsc/data/3bpa/train_300K", atomic_numbers=list(range(1, 84)))

In [3]:
len(dataset)

500

In [4]:
dataset[0].globals["energy"]

array([-17660.46], dtype=float32)

In [5]:
dataset[0].nodes["forces"]

array([[ 0.17092934,  0.132742  ,  0.7955579 ],
       [-0.89494014, -0.4486952 , -1.9094164 ],
       [ 0.31093463,  0.07569877,  1.6261265 ],
       [-0.3554449 ,  0.18552168, -0.41974518],
       [-0.05235652,  2.2182932 , -1.2863837 ],
       [-0.14820121, -0.95795447,  0.5486066 ],
       [ 0.22761995, -2.0727482 , -0.7974962 ],
       [ 0.06225767, -2.2116942 , -0.29126114],
       [ 0.06710167, -0.34712818, -0.2069372 ],
       [-0.04380163,  0.9733009 ,  2.1202154 ],
       [-0.6501094 ,  1.941089  , -1.0449272 ],
       [ 0.52957356, -0.34157458,  0.5993111 ],
       [-0.34153822,  0.3532644 , -0.29167077],
       [ 1.6354238 , -1.3044616 , -0.11956351],
       [-1.5635504 ,  1.0230376 ,  1.3580611 ],
       [-0.87120193,  0.8732088 ,  0.12832493],
       [ 0.5902793 ,  0.6289095 , -0.4972905 ],
       [-0.17116126,  0.59221995,  0.38531023],
       [ 2.6660438 , -0.91544646, -0.39223868],
       [-0.362906  ,  0.6297663 , -0.3722338 ],
       [ 0.66932124, -0.44952998, -0.088

In [6]:
import numpy as np

In [7]:
metadata = np.load("/ceph/hdd/students/kirsc/data/3bpa/train_300K/metadata.npz")
metadata["data_ids"]

array(['3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
       '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa', '3bpa',
      

In [8]:
metadata['natoms']

array([27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27