In [1]:
from nequix.data import AseDBDataset

In [2]:
dataset = AseDBDataset(file_path="/ceph/hdd/students/kirsc/data/md22/double-walled_nanotube", atomic_numbers=list(range(1, 84)))

In [3]:
len(dataset)

5032

In [4]:
dataset[0].globals["energy"]

array([-338211.44], dtype=float32)

In [5]:
dataset[0].nodes["forces"]

array([[ 0.0268341 , -0.06843463,  0.8204445 ],
       [-0.02508587,  0.09880294,  0.819265  ],
       [ 1.1830595 , -0.4366375 ,  1.0692374 ],
       ...,
       [-0.11994077,  0.01101613,  0.30582318],
       [ 0.0753898 ,  0.100384  ,  0.3075135 ],
       [-0.08113684, -0.09080487,  0.3015414 ]], dtype=float32)

In [6]:
import numpy as np

In [7]:
metadata = np.load("/ceph/hdd/students/kirsc/data/md22/double-walled_nanotube/metadata.npz")
metadata["data_ids"]

array(['md22', 'md22', 'md22', ..., 'md22', 'md22', 'md22'], dtype='<U4')

In [8]:
metadata['natoms']

array([370, 370, 370, ..., 370, 370, 370])